theme: jekyll-theme-cayman
title: 陈建宇的个人主页
description: 软件工程师 | 技术爱好者
baseurl: ""
url: "https://chenjy16.github.io"

plugins:
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .github
